some changes actions+precommit + lab2
faaant/web_kpi pull request #5
Opened 2021-09-30 10:24 UTC by faaant

2021-10-01 07:06 UTC, nosovk commented on .github/workflows/checking.yml
> +      - run: cd lab2 && npm ci && npm run prettier && npm run lint && npm run slint && cd ../
do not use cd in scripts

2021-10-01 07:06 UTC, nosovk commented on .github/workflows/checking.yml
> +      - run: cd lab2 && npm ci && npm run prettier && npm run lint && npm run slint && cd ../
workdir param for commands

2021-10-01 07:07 UTC, nosovk commented on lab2/package.json
> +    "sass": "^1.42.1"
it's a dev dep

2021-10-01 07:08 UTC, nosovk commented on lab2/pages/api/server.js
> +    await rateLimit(2, req.headers["client-ip"]);
check for x-forwarded-for

2021-10-01 07:09 UTC, nosovk commented on lab2/pages/api/server.js
> +    res.status(429).json(error);
error response format specified in RFS, use it.
JS object with errors key

2021-10-01 07:10 UTC, nosovk commented on lab2/pages/api/server.js
> +  let testAccount = await nodemailer.createTestAccount();
del

2021-10-01 07:10 UTC, nosovk commented on lab2/pages/api/server.js
> +    to: req.body.where, // list of receivers
probably should not be part of req

2021-10-01 07:11 UTC, nosovk commented on lab2/pages/api/server.js
> +    text: sanitizeHtml(req.body.letter), // plain text body
txt not html...

2021-10-01 07:11 UTC, nosovk commented on lab2/pages/api/server.js
> +  res.status(200).json({});
see responce statuses spec

2021-10-01 07:12 UTC, nosovk commented on lab2/pages/index.js
> +    const form = document.querySelector("form");
do not use DOM direct access in react

2021-10-01 07:14 UTC, nosovk commented on lab2/pages/index.js
> +        .catch((e) => console.log(e));
handle errror?

2021-10-01 07:14 UTC, nosovk commented on lab2/pages/index.js
> +          } else if (resp.status === 429) {
early return? else if else if is bit ugly

2021-10-01 07:15 UTC, nosovk commented on lab2/pages/index.js
> +          document.location.reload();
we use prevent default to avoid that effect, but ...

2021-10-01 07:15 UTC, nosovk commented on lab2/pages/index.js
> +            alert("Request failed!");
alert is not good ux

2021-10-01 07:15 UTC, nosovk commented on lab2/pages/index.js
> +      form.childNodes[1].firstChild.classList.remove(styles.visible);
optional chaining?

2021-10-01 07:16 UTC, nosovk commented on lab2/styles/Home.module.scss
> +  border: solid #303952 2px;
css vars?

2021-10-01 07:17 UTC, nosovk commented on lab2/pages/api/server.js
> +    res.status(429).json(error);
return?

2021-10-01 07:17 UTC, nosovk commented on lab2/pages/api/server.js
> +  let info = await transporter.sendMail({
no error handling?

2021-10-05 18:25 UTC, nosovk commented on .github/workflows/checking.yml
> +        working-directory: lab2
run lab1 and lab2 in parallell - they are independent.

2021-10-05 18:26 UTC, nosovk commented on .husky/pre-commit
> +cd lab2 && npm run lint && npm run prettier && npm run slint && cd ../
cd should not be invoked in hooks

2021-10-05 18:27 UTC, nosovk commented on lab2/pages/api/checking.js
> +    to: req.body.to, // list of receivers
we can send to anybody specified on frontend? Are you sure? I can abuse it...

2021-10-05 18:28 UTC, nosovk commented on lab2/pages/api/checking.js
> +    text: req.body.text, // plain text body
if text filed is missing?

2021-10-05 18:28 UTC, nosovk commented on lab2/pages/api/server.js
> +    await fetch("https://web-kpi-git-lab2-faaant.vercel.app/api/checking", {
not good at all

2021-10-05 18:31 UTC, nosovk commented on lab2/pages/index.js
> +    if (where) {
can be simplified.
```javascript
setMailErrorVisibility(!where);
return where;
```

2021-10-05 18:31 UTC, nosovk commented on lab2/styles/Home.module.scss
> +    font-size: 0.1vw;
use em\rem for fonts. not vh/vw

2021-10-05 18:33 UTC, nosovk commented
![image](https://user-images.githubusercontent.com/1398808/136082298-a696666d-4db9-4b91-b979-b93b4a81cfab.png)

2021-10-11 18:13 UTC, nosovk commented on lab2/components/Button.js
> +  if (visibility == true) {
== ? не === ? линтер не ругнулся?
Вообще можно опустить проверку как бы...

2021-10-11 18:14 UTC, nosovk commented on lab2/components/Messager.js
> +  if (message.length != 0) {
не делают такие проверки
message.length можно просто

2021-10-11 18:15 UTC, nosovk commented on lab2/package.json
> +    "prettier": "prettier --check . --no-error-on-unmatched-pattern --ignore-path .prettierignore",
--no-error-on-unmatched-pattern скорее всего не нужен

2021-10-11 18:17 UTC, nosovk requested changes

2021-10-11 18:17 UTC, nosovk commented on lab2/pages/api/server.js
> +    res.status(429).json({ message: "Too many requests!" });
https://jsonapi.org/format/#errors

2021-10-11 18:18 UTC, nosovk commented on lab2/pages/api/server.js
> +      user: "lilly.nader5@ethereal.email",
it also should be populated from env

2021-10-11 18:18 UTC, nosovk commented on lab2/pages/api/server.js
> +        .json({ message: "No one field shouldn't be empty!" });
https://jsonapi.org/format/#errors

2021-10-11 18:19 UTC, nosovk commented on lab2/pages/api/server.js
> +    from: req.body.from,
it shouldn't be defined in req

2021-10-17 16:36 UTC, nosovk commented on lab2/components/Button.js
> +  if (isDisabled === true) {
можно просто isDisabled

2021-10-17 16:39 UTC, nosovk commented
rate limit точно работает? Ручной тест показал что вроде нет

2021-10-26 21:07 UTC, nosovk commented on lab2/pages/api/server.js
> +    host: "smtp.ethereal.email",
это тоже должно быть в env

2021-10-26 21:08 UTC, nosovk commented on lab2/pages/api/server.js
> +  for (let key in req.body) {
может итерировать не так удобно как find?

2021-10-26 21:08 UTC, nosovk commented on lab2/pages/api/server.js
> +        status: "500",
500 это вутнренняя ошибка, а у тебя неверно отправленные данные

2021-10-26 21:11 UTC, nosovk commented
![image](https://user-images.githubusercontent.com/1398808/138961604-77d9d3b1-3df3-4163-8cdc-39e05a4c5d0e.png)
не вызыввется

2021-10-29 13:52 UTC, nosovk commented on lab2/pages/api/server.js
> +  const clientIP = req.headers["x-forwarded-for"][0];
нее, там строка, внутри которой массив, так ты к ней не дойдешь
```
const ip =
    (req.headers['x-forwarded-for'] || '').split(',')?.pop()?.trim() ||
    req.socket.remoteAddress;
```
что-то такое скорее

2021-11-18 21:31 UTC, nosovk commented on lab2/pages/api/server.js
> +  console.log(bodyToSend);
не нужно так делать, линтер должен был сказать - не делай так

2021-11-18 21:31 UTC, nosovk commented on lab2/pages/index.js
> +        email: e.target.Email.value,
если у нас два поля, поему бы нам их не взять через form.elements?

2021-11-23 18:17 UTC, nosovk commented on lab2/pages/index.js
> +        email: e.target.Email.value,
этот вопрос не ушел

2021-12-03 09:50 UTC, nosovk commented
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1398808/144582211-ae569d18-c84b-4ab1-8305-5cba2045fb3e.png">
broken errror handling

2021-12-03 09:52 UTC, nosovk commented on lab2/.prettierignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
probably that file could be substituted with gitignore

2021-12-03 09:54 UTC, nosovk commented on lab2/pages/api/server.js
> +  for (let key in req.body) {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2021-12-03 09:55 UTC, nosovk commented on lab2/pages/api/server.js
> +        id: new Date() + " check not null" + clientIP,
https://jsonapi.org/format/

2021-12-03 09:56 UTC, nosovk commented on lab2/pages/index.js
> +          setMessage(data.meta.data.message);
а если meta data нет, то что делать?

2021-12-27 07:19 UTC, nosovk commented on .github/workflows/checking.yml
> +          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
а нам нужны эти данные для запуска линта?

2021-12-27 07:22 UTC, nosovk commented on lab2/pages/api/server.js
> +  const transporter = nodemailer.createTransport({
транспорт как бы синглтон, нет смысла создавать его на каждый запрос, имеет смысл разово его создат вне скоупа обработчика запроса

2021-12-27 07:41 UTC, nosovk commented on lab2/package.json
> +    "prettier": "prettier --check . --ignore-path .prettierignore",
предположительно нет нужны в отдельном prettierignore при наличии gitignore

2021-12-27 07:43 UTC, nosovk commented on lab2/pages/api/server.js
> +  try {
возможно при использовании try и одного единственного await внутри имело бы смысл воспользоваться .then?

2021-12-27 07:43 UTC, nosovk commented on lab2/pages/index.js
> +        email: e.target.elements.Email.value,
где проверка на то что value существует?

2021-12-27 07:45 UTC, nosovk commented on lab2/pages/index.js
> +          if (data.meta.data?.message) {
```
         if (data.meta.data?.message) {
            setMessage(data.meta.data.message);
          } else {
            setMessage("An error may have occurred.");
          }
```
can be simplified:
```javascript
setMessage(data.meta.data?.message ?? 'An error may have occurred');
```

2021-12-27 11:48 UTC, faaant commented on lab2/package.json
> +    "prettier": "prettier --check . --ignore-path .prettierignore",
Ці два файли трошки відрізняються, тому використовую обоє.

2021-12-27 18:50 UTC, faaant commented on lab2/package.json
> +    "prettier": "prettier --check . --ignore-path .prettierignore",
вони трошки відрізняються, тому запуск іде по 2 файлах

2022-01-08 14:10 UTC, nosovk commented on lab2/components/mailEror.js
> +import styles from "../styles/components.module.scss";
файл наверное mailError.js планировался

2022-01-08 14:13 UTC, nosovk commented on lab2/pages/index.js
> +          setDisabled(true);
подозрительно повторяется, может вынести в один finally?

2022-01-14 00:18 UTC, nosovk commented
merge

2022-01-14 01:57 UTC, merged